
all: memory1 memory2 memory3 memory4 memory5a memory5b memory6

memory1:
	gcc -Wall -o memory1 memory1.c

memory2:
	gcc -Wall -o memory2 memory2.c

memory3:
	gcc -Wall -o memory3 memory3.c

memory4:
	gcc -Wall -o memory4 memory4.c

memory5a:
	gcc -Wall -o memory5a memory5a.c

memory5b:
	gcc -Wall -o memory5b memory5b.c

memory6:
	gcc -Wall -o memory6 memory6.c

clean:
	rm -f memory1 memory2 memory3 memory4 memory5a memory5b memory6 
